pluginName = Drawio Plugin
providerName = noriyuki-yagi

menu_group=Drawio Plugin
menu_label_current_diagram=Output Current Diagram to Drawio File
menu_label_select_diagrams=Select Diagrams to Drawio File